language: node_js
node_js:
  - 4

before_install:
  addons:
    firefox: "43.0.1"

before_script:
  - npm install -g bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/protractor/bin/webdriver-manager update
  - gulp serve &
  - sleep 3 # give webserver some time to start

script:
  - npm test

after_success:
  - npm run coveralls
  - npm run codacy

notifications:
  - email: false

sudo: false
